version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - /home/dliuzzo/data/wordpress:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - /home/dliuzzo/data/wordpress:/var/www/html 
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/dliuzzo/data/mariadb:/var/lib/mysql
    networks:
      inception:
networks:
  inception: