version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html 
    networks:
      - inception
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dliuzzo/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dliuzzo/data/mariadb'
networks:
  inception:
    driver: bridge